// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://znslvacilsdrurjqbuhi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpuc2x2YWNpbHNkcnVyanFidWhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NzMwMzcsImV4cCI6MjA2OTU0OTAzN30.MiqrSLUI7xnnJgpgP709ZeSfrV5pZBKT2BHKk1vN2po";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});